# Generated by Django 5.2.10 on 2026-02-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unit_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='core.course'),
        ),
        migrations.AddField(
            model_name='intake',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.intake'),
        ),
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(default='Semester 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='intake',
            name='intake_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], default='Full-time', max_length=50),
        ),
    ]
