# Generated by Django 5.2.10 on 2026-02-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_intake_course_intake_end_date_intake_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='GEN', max_length=50),
        ),
        migrations.AddField(
            model_name='intake',
            name='admission_numbers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intake',
            name='group_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_assessment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='has_cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_taught',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='assessment_total_points',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='cat_total_points',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('CAT', 'Continuous Assessment Test'), ('LabTask', 'Lab Task'), ('LessonAssessment', 'Lesson Assessment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
    ]
