# Generated by Django 5.2.10 on 2026-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_module_learningpath_assessment_module_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content for the lesson lecture notes.'),
        ),
    ]
