# Generated by Django 5.2.10 on 2026-02-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_announcement_forumtopic_forummessage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When the assessment becomes available to students', null=True),
        ),
    ]
