# Generated by Django 5.2.10 on 2026-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentlessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='audit_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='audit_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='audit_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
