# Generated by Django 5.2.10 on 2026-02-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assessment_audit_feedback_assessment_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Lesson is active and visible to students (after HOD approval and time reached)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_outcomes',
            field=models.TextField(blank=True, help_text='Learning outcomes - By the end of this lesson, students should be able to...'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='session',
            field=models.CharField(blank=True, help_text='Session name (e.g., Morning, Afternoon)', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='session_date',
            field=models.DateField(blank=True, help_text='Date of the lesson session', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='session_end',
            field=models.TimeField(blank=True, help_text='End time of the lesson', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='session_start',
            field=models.TimeField(blank=True, help_text='Start time of the lesson', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subtopic',
            field=models.CharField(blank=True, help_text='Sub-topic of the lesson', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, help_text='Main topic of the lesson', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.PositiveIntegerField(blank=True, help_text='Week number', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('critical', 'Critical'), ('lesson', 'Lesson'), ('assessment', 'Assessment'), ('enrollment', 'Enrollment'), ('approval', 'Approval')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LessonPlanActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(help_text='Time slot (e.g., 9:00-9:30)', max_length=50)),
                ('activity', models.TextField(help_text='Learning activity description')),
                ('content', models.TextField(blank=True, help_text='Specific content covered')),
                ('resources', models.TextField(blank=True, help_text='Resources/activities needed')),
                ('references', models.TextField(blank=True, help_text='References/materials')),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_activities', to='core.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
