# Generated by Django 5.2.10 on 2026-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_notification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='assessment',
            name='allow_late_submission',
            field=models.BooleanField(default=False, help_text='Allow submissions after expiry'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='When the assessment expires - submissions after get 0', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='When the assessment becomes available', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, help_text='Submitted after deadline'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_zero_graded',
            field=models.BooleanField(default=False, help_text='Graded zero due to late submission'),
        ),
    ]
