# Generated by Django 5.2.10 on 2026-02-25 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_notification_time_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name for display', max_length=50)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=20)),
                ('points_required', models.IntegerField(default=0, help_text='Minimum points to earn this badge')),
            ],
        ),
        migrations.AddField(
            model_name='lessonplanactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplanactivity',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonplanactivity',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the lesson plan (optional - for standalone plans)', max_length=255),
        ),
        migrations.AddField(
            model_name='lessonplanactivity',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plan_activities', to='core.unit'),
        ),
        migrations.AddField(
            model_name='lessonplanactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.coursegroup'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='allow_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='session_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='session_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subtopic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplanactivity',
            name='activity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lessonplanactivity',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplanactivity',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_activities', to='core.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonplanactivity',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplanactivity',
            name='resources',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lessonplanactivity',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_zero_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Rating score (0-5)', max_digits=3)),
                ('total_points', models.IntegerField(default=0, help_text='Total points earned')),
                ('completed_lessons', models.IntegerField(default=0)),
                ('completed_assessments', models.IntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Ratings',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earners', to='core.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
