# Generated by Django 5.2.10 on 2026-02-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_badge_lessonplanactivity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
