# Generated by Django 5.2.10 on 2026-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_assessment_is_active_resource_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.TextField(help_text='The encrypted/signed license key')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project License',
                'verbose_name_plural': 'Project License',
            },
        ),
    ]
